### ISSUE TITLE
Cannot rearrange mods in mods.txt

### ISSUE THREAD

**Issue by zachjord** [9d8/tmm#1]
This problem is occurring on Arch Linux.

When I try to rearrange mods in my mods.txt file and then rerun tmm, it regenerates the mods.txt file but then leaves certain folders out.

For example, the first time I run tmm in my mod folder it produces this mods.txt:

```
07_cities
01_base
09_flora_and_environment
02_ui
06_01_animations
08_creatures
11_testing
04_gampley
06_00_character_and_npc
00_super_base
06_02_ai
10_weather_atmosphere
05_01_small_textures_packs
03_audio
05_00_big_texture_packs
```
Then I go to rearrange the list to read like so:

```
00_super_base
01_base
02_ui
03_audio
04_gampley
05_00_big_texture_packs
05_01_small_textures_packs
06_00_character_and_npc
06_01_animations
06_02_ai
07_cities
08_creatures
09_flora_and_environment
10_weather_atmosphere
11_testing
```
I rerun ttm and it updates the mods.txt to and creates the symlinks accordingly:

```
00_super_base
01_base
02_ui
03_audio
04_gampley
05_00_big_texture_packs
05_01_small_textures_packs
06_00_character_and_npc
06_02_ai
08_creatures
09_flora_and_environment
10_weather_atmosphere
11_testing
```

The problem is that it has removed 2 folders, 07_cities and 06_01_animations, and does not create their sysmlinks. Further testing seems to indicate that it has something to do with the entries that are removed and their position in the mods.txt file. I've actually had this problem between 1-2 months ago when I was playing Skyrim last, but I just ignored it then.

**Comment by 9d8** [comment]
Hi,

Thank you for filing an issue. I'm sorry that I didn't notice that you posted this until now, seeing as it has been 18 days.

I will look further into this and see if I can get a fix soon.

**Comment by 9d8** [comment]
It turns out that the hash table that I wrote for keeping track of entries in the mods.txt was not properly handling hash conflicts under certain conditions. Basically, the folders that were deleted had the same hash as some other entry, so tmm would just delete them. 

I just pushed a fix for this issue, so everything should be working now.

**Comment by zachjord** [comment]
Hey, it's all good and that was a speedy fix either way! I'll see if I can give it a try sometime this weekend and if anything else pops up, I'll let you know.

Thanks!
